---
title: "Neel"
output: html_document
date: "2024-07-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(rerddap)
library(terra)
library(tidyverse)
library(patchwork)
```

Hello, have a good day! I hope you are well.
```{r}
#Loading Data
Tempinfo = info('erdCinpKfmT')
tempset = tabledap(Tempinfo)
Kelpinfo = info('erdCinpKfmRPC')
kelpset = tabledap(Kelpinfo)
Heatwavedata = rast("subset (1).nc")
```

```{r}
# Only taking significant giant kelp data

giantkelpset = kelpset %>%
  rename(date = time) %>% # this is for matching variables later for full_join
  select(station, longitude, latitude, depth, date | contains("Macrocystis_pyrifera")) %>% 
  filter(!is.na(Macrocystis_pyrifera_All_Mean) & date >= 1993-05-22) %>% # now we have all the actual values for giant kelp cover within the time frame of the temperature dataset
  group_by(date) %>% 
  mutate(percentcover = Macrocystis_pyrifera_All_Mean, meanpercentcover = mean(percentcover), meandepth = mean(depth)) %>% # make the percent cover easier to type and take the average of it across all locations
  select(-Macrocystis_pyrifera_All_Mean) %>% # removing unnecessary variables 
  relocate(percentcover, .after = date) %>% # formatting
  arrange(date) # formatting

ggplot(giantkelpset, aes(x = date, y = meanpercentcover, color = meandepth)) + geom_point() + geom_line() + geom_smooth(method = "lm") # first look at the data 
```

```{r}
# Working with the .nc for the heatwave

Heatwavedf = as.data.frame(Heatwavedata, xy = T) # turns it into a DF
dates = seq(from = as.Date("1992-12-31"), to = as.Date("2008-1-1"), by = "day") # creates dates for the dataframe

hwdf_comp = Heatwavedf %>%
  mutate(x = x - 360) %>% # make it match kelp forest dataset
  filter(x >= -118.4 | x <= -120.4) %>% 
  filter(y >= 32.8 & y <= 34.05) %>% # limit the region to the Channel Islands
  slice(18) %>% # the observation that fits the region the best
  pivot_longer(cols = 3:5482,
               names_to = "date",
               values_to = "anomalies") %>% # turns into a long format
  mutate(date = dates, data_char = as.character(date), year = as.numeric(format(date,'%Y')), month = as.numeric(format(date,'%m'))) %>% # adding the dates to the dataframe
  filter(grepl("-07-01",data_char, fixed = TRUE)) %>% # filtering for July 1st 
  select(-data_char) # getting rid of the date as character variable (date as time is still there)

```

Working with the temperature dataset (Jerry did this)
``` {r}
# Filtering for July 1st

temp_tempset = tempset %>% 
  mutate(data_char = as.character(time)) %>%
  filter(grepl("-07-01",data_char, fixed = TRUE))
```

``` {r}

# Use a for loop to fill vectors for average and maximum temperature
repvector = rep(0, 2007-1993+1)
tempvector = rep(0, 2007-1993+1)
maxtempvector = rep(0, 2007-1993+1)
for(i in 1:nrow(temp_tempset)){
  yearval = as.numeric(str_sub(temp_tempset$data_char[i], 1, 4)) # take year of date in string form and then convert to number
  index = yearval - 1992 # find the index using the year of the date minus the starting year
  repvector[index] = repvector[index] + 1
  tempvector[index] = tempvector[index] + temp_tempset$temperature[i]
  maxtempvector[index] = max(maxtempvector[index], temp_tempset$temperature[i])
}
avgtempvector = rep(0, 2007-1993+1)
for(i in 1:length(tempvector)){
  avgtempvector[i] = tempvector[i]/repvector[i]
}

date = seq(from = as.Date("1993-07-01"), to = as.Date("2007-07-01"), by = "year") # Create vectors of dates in the project
```
Making it all one dataframe
``` {r}
onedf = full_join(giantkelpset, hwdf_comp) %>% 
  select(-x, -y) # Merge the kelp dataframe and the heatwave dataframe and get rid of lat/lon for the heatwave df

temporarydf = data.frame(date, avgtempvector, maxtempvector) # create a dataframe out of the temperature and time vectors

onedf = full_join(onedf, temporarydf) # add the temperature data to the one dataframe
```
Marine Heatwaves and Extreme Heatwaves
``` {r}
hwlogical = (onedf$anomalies >= 2) # create a vector of logical values to express whether the anomaly represents a marine heatwave
extremelogical = (onedf$anomalies >= 1) # create a vector of logical values to express whether the anomaly represents an extreme marine heatwave

onedf$is.heatwave = hwlogical
onedf$is.extreme = extremelogical # adding vectors to onedf
```

```{r}
logit = function(x){
  return(log(x/(1-x)))
}

onedf = onedf %>% 
  filter(percentcover != 0) %>% 
  mutate(logit_percentcover = logit(0.01 * percentcover)) %>% 
  mutate(percentcoverperc = 0.01 * percentcover) %>% 
  mutate(date_num = as.numeric(str_sub(as.character(date),1,4))-1993)
```

```{r}
ggplot(onedf, aes(x = maxtempvector, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = avgtempvector, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = anomalies, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = date_num, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
cor.test(onedf$avgtempvector, onedf$logit_percentcover)
cor.test(onedf$maxtempvector, onedf$logit_percentcover)
cor.test(onedf$anomalies, onedf$logit_percentcover)
```

%
```{r}
library(gam)

```

```{r}
#g_model = gam(logit_percentcover ~ s(maxtempvector, df=7) + s(avgtempvector, df =4) + s(anomalies, df = 2) + date_num,
            #family = "gaussian", data = onedf)
#summary(g_model)
```

```{r}
#plot.Gam(g_model)
```
```{r}
#g_model2 = gam(percentcoverperc ~ s(maxtempvector, df=1.2) + avgtempvector + s(anomalies, df = 1.4)+
#                 date_num,
#            family = "binomial", data = onedf)
#summary(g_model2)
#plot(g_model2)
```

```{r}
hwdf_notcomp = Heatwavedf %>% 
  mutate(x = x - 360) %>% 
  filter(x >= -118.4 | x <= -120.4) %>% 
  filter(y >= 32.8 & y <= 34.05) %>%
  slice(18) %>% 
   pivot_longer(cols = 3:5482,
               names_to = "date",
               values_to = "anomalies") %>% 
  mutate(date = dates, date_char = as.character(date), year = as.numeric(format(date, '%Y'))) %>% 
  group_by(year) %>% 
  summarize(maxanomaly = max(anomalies)) %>% 
  filter(maxanomaly > -0.5) %>% 
  mutate(yearl = year-1993)
  
ggplot(hwdf_notcomp) + geom_point(aes(x = year, y = maxanomaly)) + geom_smooth(aes(x = year, y = maxanomaly)) 
ggplot(hwdf_notcomp) + geom_boxplot(aes(maxanomaly))
lm(maxanomaly ~ yearl, hwdf_notcomp)
```

```{r}
onedf = onedf %>% 
  mutate(year = date_num + 1993) %>% 
  full_join(hwdf_notcomp)
```

```{r}
g_model3 = gam(percentcoverperc ~ maxtempvector+ avgtempvector + s(maxanomaly, df = 1.2) +
                 date_num,
            family = "binomial", data = onedf)
summary(g_model3)
# graph 1 is maximum temp. graph 2 is average temp. graph 3 is maximum anomaly. graph 4 is years.
#plot.Gam(g_model3, ylab = "Effect on GAM", xlab = "Maximum Temperature (°C)", main = "Effect of Maximum Temperature on Model")
plot.Gam(g_model3, ylab = "Effect on GAM", xlab = "Average Temperature (°C)", main = "Effect of Average Temperature on Model")
#plot.Gam(g_model3, ylab = "Effect on GAM", xlab = "Maximum Anomaly (°C)", main = "Effect of Heatwaves on Model")
#plot.Gam(g_model3, ylab = "Effect on GAM", xlab = "Years since 1993", main = "Effect of Time on Model")
```

``` {r}
onedf2 = onedf %>% 
  filter(year != 1993)

a = ggplot(onedf2, aes(x = year, y = meanpercentcover)) + geom_point() + geom_smooth() + theme_bw() + labs(x = "Year", y = "Percent Cover")+ ggtitle("Time") + scale_x_continuous(breaks = seq(1994, 2007, by = 1))
b = ggplot(onedf2, aes(x = avgtempvector, y = meanpercentcover)) + geom_point() + geom_smooth() + theme_bw() + labs(x = "Average Temperature (°C)", y = "Percent Cover") + ggtitle("SST")
c = ggplot(onedf2, aes(x = maxtempvector, y = meanpercentcover)) + geom_point() + geom_smooth() + theme_bw() + labs(x = "Maximum Temperature (°C)", y = "Percent Cover") + scale_x_continuous(breaks = seq(17, 21, by = 1))
d = ggplot(onedf2, aes(x = anomalies, y = meanpercentcover)) + geom_point() + geom_smooth() + theme_bw() + labs(x = "Average Anomaly (°C)", y = "Percent Cover") + ggtitle ("MHWs")
e = ggplot(onedf2, aes(x = maxanomaly, y = meanpercentcover)) + geom_point() + geom_smooth() + theme_bw() + labs(x = "Maximum Anomaly (°C)", y = "Percent Cover") + scale_x_continuous(breaks = seq(0, 3, by = 0.5))

(a) / (b + c) / (d + e)
```



```{r}
basemaxanomaly =  1.696917
basemaxtemp = (17.28 + 18.8 + 18.98)/3
baseavgtemp = (14.14165 + 14.53518 + 13.90583)/3
```

```{r}
set.seed(1)
start = 0.08
changevector = rep(0, 8)
for(i in 0:7){
  changevector[i+1] = start + 0.1*i
}
nmt = rep(0,8)
for(i in 1:8){
  nmt[i] = basemaxtemp + changevector[i]
}
nat = rep(0,8)
for(i in 1:8){
  nat[i] = baseavgtemp + changevector[i]
}
anomalyv = rep(basemaxanomaly + rnorm(1, 0, 1),8)
yr2050 = rep(2050-1993, 8)
predict_df = data.frame(nmt, nat, anomalyv,yr2050)
colnames(predict_df) = c('maxtempvector', 'avgtempvector', 'maxanomaly', 'date_num')
```

```{r}
something = predict.Gam(g_model3, predict_df)
something = exp(something)
something = something/(1+something)
finaldf = data.frame(something, changevector)
finaldf = finaldf %>% 
  mutate(percentcover = something * 100)
ggplot(finaldf) + geom_point(aes(x = changevector, y = percentcover)) + geom_smooth(aes(x = changevector, y = percentcover)) + labs(x = "Net Average SST Change (°C)", y = "Giant Kelp Percent Cover", title = "Kelp Cover in 2050", subtitle = "Under Different Warming Scenarios") + theme_bw() + ylim(1.8, 1.9)
```

```{r}
at = rep(baseavgtemp + 0.78, 33)
mt = rep(baseavgtemp + 0.78, 33)
anom = rep(0, 33)
for(i in 1: 33){
  anom[i] = basemaxanomaly + 0.1* (i-1)
}
yr2050_2 = rep(2050-1993, 33)
predict2_df = data.frame(mt, at, anom, yr2050_2)
colnames(predict2_df) = c('maxtempvector', 'avgtempvector', 'maxanomaly', 'date_num')
```

```{r}
preds = predict.Gam(g_model3, predict2_df)
preds = exp(preds)
preds = preds/(1+preds)
final2df = data.frame(preds, anom)
final2df = final2df %>% 
  mutate(percentcover = preds *100)
ggplot(final2df) + geom_point(aes(x = anom, y = percentcover)) + geom_smooth(aes(x = anom, y = percentcover)) + labs(x = "Maximum Heat Wave Intensity (Anomaly in °C)", y = "Giant Kelp Percent Cover", title = "Kelp Cover Under RCP 8.5 Conditions") + theme_bw()
```
