---
title: "Rui Huang"
output: html_document
date: "2024-07-08"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(terra)
library(rerddap)
library(tidyverse)
library(gam)
```


```{r}
#Loading dataset
Tempinfo = info('erdCinpKfmT')
tempset = tabledap(Tempinfo)
Kelpinfo = info('erdCinpKfmRPC')
kelpset = tabledap(Kelpinfo)
Heatwavedata = rast("subset (1).nc")
```
```{r}
# Adding character in dataframe for temporary dataset
temp_tempset = tempset %>% 
  mutate(data_char = as.character(time))
```

```{r}
#Filters for July 1st
temp_tempset = temp_tempset %>% 
  filter(grepl("-07-01",data_char, fixed = TRUE))
```

```{r}
#Look for avg temerature and max temperature via iteration
repvector = rep(0, 2007-1993+1)
tempvector = rep(0, 2007-1993+1)
maxtempvector = rep(0, 2007-1993+1)
for(i in 1:nrow(temp_tempset)){
  yearval = as.numeric(str_sub(temp_tempset$data_char[i], 1, 4))
  index = yearval - 1992 
  repvector[index] = repvector[index] + 1
  tempvector[index] = tempvector[index] + temp_tempset$temperature[i]
  maxtempvector[index] = max(maxtempvector[index], temp_tempset$temperature[i])
}
avgtempvector = rep(0, 2007-1993+1)
for(i in 1:length(tempvector)){
  avgtempvector[i] = tempvector[i]/repvector[i]
}
```

```{r}
#Plots data
timevector = c(0: (2007-1993))
#tempdf = data.frame(avgtempvector, timevector)
ggplot() +
  geom_point(aes(x = timevector, y = avgtempvector))
ggplot() +
  geom_point(aes(x = timevector, y = maxtempvector))
lrdf = data.frame(maxtempvector,timevector)
lm(maxtempvector~timevector ,data = lrdf)
ggplot(lrdf) + geom_boxplot(aes(maxtempvector))
```

```{r}
#Creates heatwave dataframe
Heatwavedf = as.data.frame(Heatwavedata, xy = T) # turns it into a DF
dates = seq(from = as.Date("1992-12-31"), to = as.Date("2008-1-1"), by = "day") # creates dates for the dataframe
 
hwdf_comp = Heatwavedf %>%
  mutate(x = x - 360) %>% 
  filter(x >= -118.4 | x <= -120.4) %>% 
  filter(y >= 32.8 & y <= 34.05) %>% # limit the region to the Channel Islands
  slice(18) %>% # the observation that fits the region the best
  pivot_longer(cols = 3:5482,
               names_to = "date",
               values_to = "anomalies") %>% # turns into a long format
  mutate(date = dates, data_char = as.character(date)) %>% # adding the dates to the dataframe
  filter(grepl("-07-01",data_char, fixed = TRUE)) %>% # filtering for July 1st
  select(-data_char) # getting rid of the date as character variable (date as time is still there)
```


```{r}
giantkelpset = kelpset %>%
  rename(date = time) %>% # this is for matching variables later for full_join
  select(station, longitude, latitude, depth, date | contains("Macrocystis_pyrifera")) %>% 
  filter(!is.na(Macrocystis_pyrifera_All_Mean) & date >= 1993-05-22) %>% # now we have all the actual values for giant kelp cover within the time frame of the temperature dataset
  group_by(date) %>% 
  mutate(percentcover = Macrocystis_pyrifera_All_Mean, meanpercentcover = mean(percentcover), meandepth = mean(depth)) %>% # make the percent cover easier to type and take the average of it across all locations
  select(-Macrocystis_pyrifera_All_Mean) %>% # removing unnecessary variables 
  relocate(percentcover, .after = date) %>% # formatting
  arrange(date) # formatting

```

```{r}
date = seq(from = as.Date("1993-07-01"), to = as.Date("2007-07-01"), by = "year")
onedf = full_join(giantkelpset, hwdf_comp) %>% 
  select(-x, -y) # Merge the kelp dataframe and the heatwave dataframe and get rid of lat/lon for the heatwave df

temporarydf = data.frame(date, avgtempvector, maxtempvector) # create a dataframe out of the temperature and time vectors

onedf = full_join(onedf, temporarydf) # add the temperature data to the one dataframe
```
```{r}
logit = function(x){
  return(log(x/(1-x)))
}

onedf = onedf %>% 
  filter(percentcover != 0) %>% 
  mutate(logit_percentcover = logit(0.01 * percentcover)) %>% 
  mutate(percentcoverperc = 0.01 * percentcover) %>% 
  mutate(date_num = as.numeric(str_sub(as.character(date),1,4))-1993)
```

```{r}
print("a")
citation("base")
```


```{r}
ggplot(onedf, aes(x = maxtempvector, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = avgtempvector, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = anomalies, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
ggplot(onedf, aes(x = date_num, y = logit_percentcover)) +
  geom_point() +
  geom_smooth()
cor.test(onedf$avgtempvector, onedf$logit_percentcover)
cor.test(onedf$maxtempvector, onedf$logit_percentcover)
cor.test(onedf$anomalies, onedf$logit_percentcover)
```

%
```{r}
library(gam)

```

```{r}
g_model = gam(logit_percentcover ~ s(maxtempvector, df=7) + s(avgtempvector, df =4) + s(anomalies, df = 2) + date_num,
            family = "gaussian", data = onedf)
summary(g_model)
```

```{r}
plot.Gam(g_model)
```
```{r}
g_model2 = gam(percentcoverperc ~ s(maxtempvector, df=1.2) + avgtempvector + s(anomalies, df = 1.4)+
                 date_num,
            family = "binomial", data = onedf)
summary(g_model2)
plot(g_model2)
```

```{r}
hwdf_notcomp = Heatwavedf %>% 
  mutate(x = x - 360) %>% 
  filter(x >= -118.4 | x <= -120.4) %>% 
  filter(y >= 32.8 & y <= 34.05) %>%
  slice(18) %>% 
   pivot_longer(cols = 3:5482,
               names_to = "date",
               values_to = "anomalies") %>% 
  mutate(date = dates, date_char = as.character(date), year = as.numeric(format(date, '%Y'))) %>% 
  group_by(year) %>% 
  summarize(maxanomaly = max(anomalies)) %>% 
  filter(maxanomaly > -0.5) %>% 
  mutate(yearl = year-1993)
  
ggplot(hwdf_notcomp) + geom_point(aes(x = year, y = maxanomaly)) + geom_smooth(aes(x = year, y = maxanomaly)) 
ggplot(hwdf_notcomp) + geom_boxplot(aes(maxanomaly))
lm(maxanomaly ~ yearl, hwdf_notcomp)
```

```{r}

```

```{r}
onedf = onedf %>% 
  mutate(year = date_num + 1993) %>% 
  full_join(hwdf_notcomp)
```

```{r}
g_model3 = gam(percentcoverperc ~ maxtempvector+ avgtempvector + s(maxanomaly, df = 1.2)+
                 date_num,
            family = "binomial", data = onedf)
summary(g_model3)
plot(g_model3)
```
```{r}
basemaxanomaly =  1.696917
basemaxtemp = (17.28 + 18.8 + 18.98)/3
baseavgtemp = (14.14165 + 14.53518 + 13.90583)/3
```

```{r}
set.seed(1)
start = 0.08
changevector = rep(0, 8)
for(i in 0:7){
  changevector[i+1] = start + 0.1*i
}
nmt = rep(0,8)
for(i in 1:8){
  nmt[i] = basemaxtemp + changevector[i]
}
nat = rep(0,8)
for(i in 1:8){
  nat[i] = baseavgtemp + changevector[i]
}
anomalyv = rep(basemaxanomaly + rnorm(1, 0, 1),8)
yr2050 = rep(2050-1993, 8)
predict_df = data.frame(nmt, nat, anomalyv,yr2050)
colnames(predict_df) = c('maxtempvector', 'avgtempvector', 'maxanomaly', 'date_num')
```

```{r}
something = predict.Gam(g_model3, predict_df)
something = exp(something)
something = something/(1+something)
finaldf = data.frame(something, changevector)
finaldf = finaldf %>% 
  mutate(percentcover = something * 100)
ggplot(finaldf) + geom_point(aes(x = changevector, y = percentcover)) + geom_smooth(aes(x = changevector, y = percentcover))
```
--end of code--


```{r}
at = rep(baseavgtemp + 0.78, 33)
mt = rep(baseavgtemp + 0.78, 33)
anom = rep(0, )
```
























